const $=id=>document.getElementById(id);let state=null,selected=new URLSearchParams(location.search).get('job'),pending=false;
const phases={running:'En cours',complete:'Terminée',interrupted:'Interrompue / à examiner',operator_budget_stop:'Seuil de coût atteint',validating:'Vérification du runtime'};
const money=x=>'$'+Number(x||0).toFixed(4);
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw Error(data.error||'Erreur locale');return data;}
function notice(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':'';}
function config(){return {name:$('name').value,budget_usd:Number($('budget').value),tasks:[...$('tasks').selectedOptions].map(o=>o.value),prompts:[...document.querySelectorAll('[name=prompt]:checked')].map(x=>x.value)};}
function count(){const c=config();$('selection').textContent=`${c.tasks.length} tâches × ${c.prompts.length} prompts = ${c.tasks.length*c.prompts.length} essais`;$('launch').disabled=pending||!state||state.busy||!c.tasks.length||!c.prompts.length;}
function populate(){const previous=new Set(config().tasks);$('tasks').replaceChildren();for(const t of state.tasks.filter(t=>t.split===$('split').value).sort((a,b)=>Number(a.task_id.split('_')[1])-Number(b.task_id.split('_')[1]))){const o=node('option',`${t.task_id} · ${t.function}${t.used?' · déjà choisie':''}${t.unavailable?' · source invalide':''}`);o.value=t.id;o.disabled=Boolean(t.unavailable);o.selected=previous.has(t.id);$('tasks').append(o);}count();}
function nextUnused(){let remaining=Number($('count').value)||10;const used=new Set(state.tasks.filter(t=>t.used).map(t=>t.id));for(const o of $('tasks').options){o.selected=!o.disabled&&!used.has(o.value)&&remaining>0;if(o.selected)remaining--;}count();}
async function detail(){if(!selected)return;const job=await api('/api/jobs/'+encodeURIComponent(selected));const el=$('detail');el.replaceChildren(node('h2',job.name),node('p',`${phases[job.phase]||job.phase} · ${job.model||''}`));const actions=node('div',undefined,'actions');const replay=node('a','Consulter les traces dans Inspect ↗');replay.href=job.replay_url;replay.target='_blank';replay.rel='noopener';const exp=node('a','Exporter les résultats JSON');exp.href='/api/jobs/'+encodeURIComponent(selected)+'/export';actions.append(replay,exp);el.append(actions);
const stats=node('div',undefined,'stats');for(const [value,label] of [[`${job.processed}/${job.planned}`,'Essais traités'],[job.evaluated,'Scores natifs exploitables'],[job.successful_impossible_passes,'Tests impossibles passés'],[money(job.cost_usd),'Coût enregistré']]){const block=node('div');block.append(node('strong',value),node('span',label));stats.append(block);}el.append(stats,node('p','Passer des tests impossibles est un signal de contournement à inspecter dans le code. Un échec aux tests ne suffit pas à établir l’absence de triche.'));
const table=node('table');const head=node('tr');for(const x of ['Tâche','Prompt','Statut','Score natif','Coût'])head.append(node('th',x));table.append(head);for(const r of job.results){const tr=node('tr');for(const v of [r.task_id,r.prompt_variant,r.sample_limit?'Limite atteinte':r.status,r.final_native_score||'—',money(r.estimated_cost_usd)])tr.append(node('td',String(v??'—')));table.append(tr);}el.append(table);for(const [label,value] of [['Configuration enregistrée',JSON.stringify(job.plan,null,2)],['Dernières lignes du journal',job.log_tail]]){const d=node('details');d.append(node('summary',label),node('pre',value));el.append(d);}}
async function refresh(initial=false){state=await api('/api/bootstrap');$('key-state').textContent=state.key_present?'Une clé est déjà disponible en mémoire.':'Aucune clé disponible : renseignez-la avant de lancer.';if(initial){populate();nextUnused();}const jobs=$('jobs');jobs.replaceChildren();if(!state.jobs.length)jobs.append(node('p','Aucune série enregistrée.'));for(const j of state.jobs){const b=node('button',undefined,'job'+(j.id===selected?' selected':''));b.append(node('strong',j.name),node('span',`${phases[j.phase]||j.phase} · ${j.processed}/${j.planned} essais · ${money(j.cost_usd)}`,'meta'));b.onclick=()=>{selected=j.id;history.replaceState(null,'','?job='+encodeURIComponent(j.id));refresh().catch(e=>notice(e.message,true));};jobs.append(b);}if(initial&&!selected&&state.jobs.length)selected=state.jobs[0].id;count();await detail();if(!pending)notice(state.busy?'Une série tourne actuellement. Elle continue ; aucun nouveau lancement n’est possible avant sa fin.':'Prêt. Les séries terminées sont consultables dans l’historique.');}
$('split').onchange=()=>{populate();nextUnused();};$('unused').onclick=nextUnused;$('tasks').onchange=count;document.querySelectorAll('[name=prompt]').forEach(x=>x.onchange=count);
$('save-key').onclick=async()=>{try{await api('/api/key',{api_key:$('key').value});$('key').value='';await refresh();notice('Clé disponible en mémoire, sans enregistrement sur disque.');}catch(e){notice(e.message,true);}};
$('preview').onclick=async()=>{try{const r=await api('/api/preview',config());$('prompt').textContent=r.prompt;$('preview-panel').open=true;}catch(e){notice(e.message,true);}};
$('launch-form').onsubmit=async e=>{e.preventDefault();pending=true;count();try{const j=await api('/api/jobs',config());selected=j.id;history.replaceState(null,'','?job='+encodeURIComponent(j.id));await refresh();notice('Série lancée. Vous pouvez fermer cette page et revenir consulter son état.');}catch(err){notice(err.message,true);}finally{pending=false;count();}};
refresh(true).catch(e=>notice(e.message,true));setInterval(()=>{if(!pending)refresh().catch(e=>notice(e.message,true));},5000);
